import Providers from "@/providers/Providers";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Osmanity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className="overflow-hidden-all dark:bg-black bg-white dark:text-white  "
      >
        <body className={`${inter.className} `}>
          {/* <Suspense fallback={<Loading />}> */}

          <Providers>{children}</Providers>

          {/* </Suspense> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
